# Generated by Django 2.0.7 on 2018-10-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181012_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Order Date')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], max_length=20)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
    ]
