# Generated by Django 2.0.7 on 2018-10-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Contact',
            new_name='contact',
        ),
    ]
