# Generated by Django 2.0.7 on 2018-10-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181012_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
