# Generated by Django 2.0.7 on 2018-10-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181015_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
