# Generated by Django 2.0.7 on 2018-10-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20181017_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='orderno',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Book'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Cart'),
        ),
    ]
